name: clean_architecture_bloc
description: This is a Clean Architecture Pattern with Bloc.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  #state management
  flutter_bloc: ^8.1.1
  #functional programming
  dartz: ^0.10.1
  #value equality
  equatable: ^2.0.5
  #service locator
  get_it: ^7.2.0
  #remote api
  http: ^0.13.5
  dio: ^4.0.6
  internet_connection_checker: ^1.0.0+1
  #local cached data
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
